//@version=5
strategy("dynamic-EMA-RSI-SQ-LEO", overlay=true, initial_capital = 300, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_type=strategy.commission.percent, commission_value=0.1)
//this strategy has fixed loss and profit

// Define start and end date inputs
startDate = input.time(defval = timestamp("2022-11-01"), title = "Start Date")
//endDate = input.time(defval = timestamp("2024-03-15"), title = "End Date")

atrPeriod = input(10, "ATR Length")
factor = input.float(3.0, "Factor", step = 0.01)
rsi_len = input(14, "RSI Length")


[_, direction] = ta.supertrend(factor, atrPeriod)
rsi = ta.rsi(close, rsi_len )

length = input(20, title="BB Length")
mult = input(2.0,title="BB MultFactor")
lengthKC=input(20, title="KC Length")
multKC = input(1.5, title="KC MultFactor")

useTrueRange = input(true, title="Use TrueRange (KC)")

// Calculate BB
source = close
basis = ta.sma(source, length)
dev = multKC * ta.stdev(source, length)
upperBB = basis + dev
lowerBB = basis - dev

// Calculate KC
ma = ta.sma(source, lengthKC)
range_ = useTrueRange ? ta.tr : (high - low)
rangema = ta.sma(range_, lengthKC)
upperKC = ma + rangema * multKC
lowerKC = ma - rangema * multKC

sqzOn  = (lowerBB > lowerKC) and (upperBB < upperKC)
sqzOff = (lowerBB < lowerKC) and (upperBB > upperKC)
noSqz  = (sqzOn == false) and (sqzOff == false)


//@variable Stop-loss price for exit commands.
var float stopLoss   = na
var float stopLoss_l   = na
var float stopLoss_s   = na
//@variable Take-profit price for exit commands.
var float takeProfit = na
var float takeProfit_l = na
var float takeProfit_s = na

var float stopLoss_long   = na
//@variable Take-profit price for exit commands.
var float stopLoss_short = na



src = close

// Input options for EMAs
emaS_value = input.int(12, minval=1, title="EMA Small - Value")
emaS = ta.ema(close, emaS_value)
emaB_value = input.int(21, minval=1, title="EMA Big - Value")
emaB = ta.ema(close, emaB_value)

EMA_UpTrend_color = input(color.green, title="EMA UpTrend Color")
EMA_DownTrend_color = input(#ff0000, title="EMA DownTrend Color")

// Rules For Up and Down EMA trends
EMA_UpTrend = emaS >= emaB
EMA_DownTrend = emaS < emaB

// Rules for Arrows by using EMAs Crossover state
var float crossover = na
// Determine crossover state
if (crossover == 1)
    crossover := na
else if (EMA_UpTrend[1] and EMA_DownTrend)
    crossover := -1
else if (crossover == -1)
    crossover := na
else if (EMA_DownTrend[1] and EMA_UpTrend)
    crossover := 1

var float count = 0

// Check if the current bar's time is within the specified date range
inDateRange = time >= startDate //and time <= endDate

longcondition = EMA_UpTrend and rsi > 60 and sqzOff and inDateRange and strategy.opentrades == 0// and count == 0
//alertcondition(longcondition, title="Enter Long", message="Long condition met. Consider entering a long position.")
shortcondition = EMA_DownTrend and rsi < 40 and sqzOff and inDateRange and strategy.opentrades == 0//and count == 1
//alertcondition(shortcondition, title="Enter Short", message="Long condition met. Consider entering a short position.")


takeProfit_l := close * 1.6
takeProfit_s := close * 0.97

stop_distance = input(5, "SL distance")
stopLoss_l  := ta.lowest(low, stop_distance)
stopLoss_s  := ta.highest(high, stop_distance)

if longcondition
    //if strategy.opentrades.size() > 0
    //strategy.close_all()
    //stopLoss   := stopLoss_l
    stopLoss_long  := stopLoss_l
    //takeProfit := takeProfit_l
    strategy.entry("long", strategy.long)
    strategy.exit("exit long", "long", stop = stopLoss_long, alert_message="Long condition met")
    count := 1
    stopLoss_short  := na

if shortcondition
    //stopLoss   := stopLoss_s
    stopLoss_short  := stopLoss_s
    //takeProfit := takeProfit_s
    strategy.entry("short", strategy.short)
    strategy.exit("exit short", "short", stop = stopLoss_short, alert_message="Short condition met")
    count := 0
    stopLoss_long  := na
    

// Dynamic exit conditions based on RSI for an open long position
exitLongCondition = strategy.position_size > 0 and EMA_DownTrend and rsi < 45
//alertcondition(exitLongCondition, title="Exit Long", message="Conditions met to exit long position.")

if exitLongCondition
    strategy.close("long", alert_message="Conditions met to exit long position.")   

exitShortCondition = strategy.position_size < 0 and EMA_UpTrend and rsi > 55
//alertcondition(exitShortCondition, title="Exit Long", message="Conditions met to exit long position.")
// Dynamic exit conditions based on RSI for an open short position
if exitShortCondition
    strategy.close("short", alert_message="Conditions met to exit exit position.")

//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)
plot(stopLoss_long, "SL", color.red, style = plot.style_circles)
plot(stopLoss_short, "SL", color.rgb(76, 129, 175), style = plot.style_circles)
//plot(takeProfit, "TP", color.green, style = plot.style_circles)
